[package]
name = "physarium_art"
version = "0.1.0"
authors = ["SKittan"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.10.0"
nannou = "0.18.1"
rand = "0.8.5"