[package]
name = "physarium_art"
version = "0.1.0"
authors = ["SKittan"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.10.0"
pollster = "0.2.5"
rand = "0.8.5"
winit = "0.26.1"
wgpu = "0.13.1"